version: '3'
services:
  db:
    build:
      context: db
    volumes:
      - ./db/data_dump:/var/opt/mssql

  app:
    build:
      context: app
    volumes:
      - ./app/log:/tmp/mylog
    depends_on:
        - db
